{% set sdata = load_setup_py_data() %}

package:
  name: datashader-examples
  version: {{ sdata['version'] }}

source:
  path: ../..

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - param
  run:
    - python {{ sdata['python_requires'] }}
    - datashader

    {% for dep in sdata['extras_require']['examples'] %}
    - {{ dep }}
    {% endfor %}


test:
  imports:
    - datashader
  requires:
    {% for dep in sdata['extras_require']['test'] %}
    - {{ dep }}
    {% endfor %}
  commands:
    - py.test --verbose --pyargs datashader
    # TODO: just one during setting up of tests
    - pytest --nbsmoke-run examples/getting_started/1_Introduction.ipynb

about:
  home: {{ sdata['url'] }}
  summary: {{ sdata['description'] }}
  license: {{ sdata['license'] }}
