# We deliberately don't use travis's language=python option because
# we install miniconda and use conda to get python. Additionally, 
# Travis's auto-install of python doesn't work on osx images (see
# https://github.com/travis-ci/travis-ci/issues/4729).
language: generic

sudo: false

os:
  - linux

stages:
  - test
  - name: conda_dev_package
    if: (branch = packaging)

jobs:
  include:
    - &default
      stage: test
      env:
        - PYTHON_VERSION=3.6
      before_install:
        # brew-installed geos interferes with cartopy?
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            brew uninstall --ignore-dependencies geos gdal postgis;
          fi
        ## use system python to install doit, then use doit to install miniconda
        - easy_install --user doit==0.29.0 pyct && ~/.local/bin/doit install_miniconda && rm -f .doit.db
        - export PATH="$HOME/miniconda/bin:$PATH"
        ## install doit into miniconda
        - conda install -y -c pyviz/label/dev -c conda-forge pyct
        - doit ci_configure_conda
      install:
        - doit create_env --name=test-environment --python=$PYTHON_VERSION
        - source activate test-environment
        - doit conda_develop_install --channel=pyviz/label/dev --channel=conda-forge
      script:
        - doit all_tests

#    - <<: *default
#      stage: test
#      script:

    - <<: *default
      stage: conda_dev_package
      install:
        - export VERSIONHACK=$(python -c "import subprocess;desc=subprocess.check_output(['git','describe','--long']).decode('utf8');v,commits=desc.split('-')[0:2];newv=[int(x) for x in v.split('.')];newv[-1]+=1;print('.'.join(str(x) for x in newv)+'.dev'+commits)")      
        - doit build_conda_package --channel conda-forge
      script: true
#        - doit upload_conda_package --token=$CONDA_UPLOAD_TOKEN

notifications:
  email: false
