# TODO before merge:
#  * what channels?
#  * restore previous sections
#  * restore guards for various sections
        
language: generic

sudo: false

os:
  - linux

stages:
  - test
  - name: conda_dev_package
    if: (branch = packaging)

jobs:
  include:

    - &python_default
      stage: test
      env:
        - DESC="pip"
        - PYENV_VERSION=3.6
      before_install: pip install tox py2venv
      install: true
      script: tox -e py${PYENV_VERSION//./}

    - <<: *python_default
      env: PYENV_VERSION=2.7

    - &conda_default
      stage: test
      env:
        - DESC="conda"
        - PYTHON_VERSION=3.6
      before_install:
        # brew-installed geos interferes with cartopy?
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            brew uninstall --ignore-dependencies geos gdal postgis;
          fi
        ## use system python to install doit, then use doit to install miniconda
        - easy_install --user doit==0.29.0 pyct && ~/.local/bin/doit install_miniconda && rm -f .doit.db
        - export PATH="$HOME/miniconda/bin:$PATH"
        ## install doit into miniconda
        - conda install -y -c pyviz/label/dev -c conda-forge pyct
        - doit ci_configure_conda
      install:
        - doit create_env --name=test-environment --python=$PYTHON_VERSION
        - source activate test-environment
        - doit conda_develop_install --channel=pyviz/label/dev --channel=conda-forge
        - doit capture_conda_env
      script:
        - doit all_tests

#    - <<: *conda_default
#      stage: test
#      script:

    - <<: *conda_default
      stage: conda_dev_package
      install:
        - doit build_conda_package --type base --channel pyviz/label/dev --channel conda-forge
        - doit build_conda_package --type examples --channel pyviz/label/dev --channel conda-forge
      script: true
#        - doit upload_conda_package --token=$CONDA_UPLOAD_TOKEN

notifications:
  email: false
