# TODO before merge:
#  * what channels?
#  * restore previous sections
#  * restore guards for various sections
        
language: generic

sudo: false

os:
  - linux

env:
  global:
    - DOIT="doit --db-file=$HOME/extracache/.doitdb"

cache:
  directories:
    - $HOME/miniconda
    - $HOME/extracache

before_cache:
  - rm -rf $HOME/miniconda/pkgs

stages:
  - test
  - name: conda_dev_package
    if: (branch = packaging)

jobs:
  include:

    - &python_default
      stage: test
      env:
        - DESC="pip"
        - PYENV_VERSION=3.6
      before_install: pip install tox py2venv
      install: true
      script: tox -e py${PYENV_VERSION//./}

    - <<: *python_default
      env:
        - DESC="pip"
        - PYENV_VERSION=2.7

    - &conda_default
      stage: test
      env:
        - DESC="conda develop"
        - PYENV_VERSION=3.6
      before_install:
        # brew-installed geos interferes with conda's cartopy?
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            brew uninstall --ignore-dependencies geos gdal postgis;
          fi
        # install doit/pyct and use to install miniconda...
        - pip install pyct && $DOIT install_miniconda
        - export PATH="$HOME/miniconda/bin:$PATH" && hash -r
        # ...and now install doit/pyct into miniconda
        # (could use conda, but need doit py2+py3 on defaults+conda-forge)
        - pip install pyct
        - $DOIT ci_configure_conda -c conda-forge
      install:
        - $DOIT create_env --name=test-environment --python=$PYENV_VERSION
        - source activate test-environment
        - $DOIT conda_develop_install -c pyviz/label/dev -c conda-forge
        - $DOIT capture_conda_env
      script:
        - $DOIT all_tests

    - <<: *conda_default
      env:
        - DESC="conda develop"
        - PYENV_VERSION=2.7

    - <<: *conda_default
      stage: conda_dev_package
      install:
        - $DOIT build_conda_package --type base -c pyviz/label/dev -c conda-forge
        - $DOIT build_conda_package --type examples -c pyviz/label/dev -c conda-forge
      script: true
#        - $DOIT upload_conda_package --token=$CONDA_UPLOAD_TOKEN

notifications:
  email: false
